// frontend/src/components/MarketSentimentGauge.tsx
"use client";

import React, { useState, useEffect, useCallback, useRef } from "react";
import ReactECharts from "echarts-for-react";
import { Icon } from "@/components/ui/Icon";
import { Skeleton } from "@/components/ui/Skeleton";
import { useTheme } from "@/components/ThemeProvider";
import { cn } from "@/lib/utils";

interface SentimentData {
  value: number;
  details: Record<string, string>;
}

export const MarketSentimentGauge = () => {
  const [data, setData] = useState<SentimentData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isError, setIsError] = useState(false);
  const [isInitializing, setIsInitializing] = useState(false);
  const { theme } = useTheme();
  const echartsRef = useRef<any>(null);

  const fetchMetric = useCallback(async () => {
    try {
      const response = await fetch("/api/market-index");
      if (response.status === 200) {
        const result = await response.json();
        setData(result);
        setIsError(false);
        setIsInitializing(false);
        setIsLoading(false);
      } else if (response.status === 202) {
        setIsInitializing(true);
        setIsError(false);
        setIsLoading(false);
      } else {
        throw new Error("Server Error");
      }
    } catch (e) {
      console.error("Failed to fetch market index:", e);
      setIsError(true);
      setIsInitializing(false);
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchMetric();
    const interval = setInterval(() => {
      if (document.visibilityState === "visible") fetchMetric();
    }, 10 * 60 * 1000);

    return () => clearInterval(interval);
  }, [fetchMetric]);

  const formatKey = (key: string) => {
    const map: any = { rsi: "RSI", vix: "VIX", valuation: "估值", macro: "宏观" };
    return map[key] || key;
  };

  const option = {
    series: [
      {
        type: "gauge",
        startAngle: 190,
        endAngle: -10,
        center: ["50%", "70%"],
        radius: "100%",
        min: 0,
        max: 100,
        splitNumber: 5,
        axisLine: {
          lineStyle: {
            width: 6,
            color: [
              [0.3, "#10b981"],
              [0.5, "#34d399"],
              [0.7, "#fbbf24"],
              [0.85, "#f97316"],
              [1, "#ef4444"],
            ],
          },
        },
        pointer: {
          icon: "path://M12.8,0.7l12,10.1c0.4,0.3,0.4,0.9,0.1,1.2c-0.3,0.4-0.9,0.4-1.2,0.1L12,2.3L0.3,12.1c-0.4,0.3-0.9,0.3-1.2-0.1c-0.3-0.4-0.3-0.9,0.1-1.2L11.2,0.7C11.7,0.3,12.3,0.3,12.8,0.7z",
          length: "10%",
          width: 4,
          offsetCenter: [0, "-50%"],
          itemStyle: { color: isError ? "#64748b" : "auto" },
        },
        axisTick: { show: false },
        splitLine: { show: false },
        axisLabel: {
          color: theme === "dark" ? "#94a3b8" : "#64748b",
          fontSize: 9,
          distance: -40,
          formatter: function (v: number) {
            if (v === 15) return "极度恐惧";
            if (v === 85) return "极度贪婪";
            return "";
          },
        },
        detail: {
          fontSize: 18,
          offsetCenter: [0, "20%"],
          valueAnimation: true,
          formatter: "{value}",
          color: isError ? "#64748b" : "auto",
          fontWeight: "800",
        },
        data: [{ value: data?.value || 0 }],
      },
    ],
  };

  return (
    <div className={cn(
      "card p-4 flex flex-col relative transition-all",
      isError && "border-rose-200 dark:border-rose-900/30"
    )}>
      <div className="flex justify-between items-center mb-1 text-[var(--text-primary)]">
        <div className="flex items-center gap-2">
          <h3 className="text-sm font-black">市场情绪指数</h3>
          {isError && (
            <span className="text-[0.7rem] font-bold px-1.5 py-0.5 rounded bg-rose-100 text-[var(--danger-color)] uppercase">离线</span>
          )}
          {isInitializing && !isError && (
            <span className="text-[0.7rem] font-bold px-1.5 py-0.5 rounded bg-amber-100 text-[var(--warning-color)] uppercase">同步中</span>
          )}
        </div>
        <span className="text-xs text-[var(--text-tertiary)] font-semibold">10min 自动刷新</span>
      </div>

      <div className="h-[110px] w-full flex items-center justify-center relative">
        {isLoading && !data ? (
          <Skeleton width="100px" height="100px" radius="50%" />
        ) : (
          <ReactECharts
            ref={echartsRef}
            option={option}
            style={{ height: "100%", width: "100%" }}
            className={cn("transition-all duration-500", isError && "grayscale opacity-50")}
          />
        )}

        {isError && (
          <div className="absolute inset-0 flex items-center justify-center z-10 bg-white/10 dark:bg-black/10 backdrop-blur-[1px]">
            <button 
              onClick={fetchMetric}
              className="p-2 rounded-lg bg-[var(--card-bg)] border border-[var(--border-color)] shadow-sm hover:scale-110 transition-transform"
            >
              <Icon name="lucide:refresh-cw" className="size-5 text-[var(--text-secondary)]" />
            </button>
          </div>
        )}
      </div>

      {data && (
        <div className="grid grid-cols-4 gap-2 mt-2 pt-3 border-t border-dashed border-[var(--border-color)]">
          {Object.entries(data.details).map(([key, val]) => (
            <div key={key} className="flex flex-col items-center">
              <span className="text-xs text-[var(--text-secondary)] mb-0.5">{formatKey(key)}</span>
              <span className="text-sm font-black text-[var(--text-primary)]">{val}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

// frontend/app/components/MarketSentimentGauge.vue
<template>
  <div class="sentiment-gauge-container" :class="{ 'is-loading': pending || isInitializing, 'is-error': isError }">
    <div class="gauge-header">
      <div class="title-group">
        <h3 class="text-base font-bold">市场情绪指数</h3>
        <div v-if="isError" class="status-indicator error">离线</div>
        <div v-else-if="isInitializing" class="status-indicator warning">同步中</div>
      </div>
      <span class="text-[10px] text-gray-400">10min 自动刷新</span>
    </div>
    
    <!-- Skeleton while loading (initial) -->
    <div v-if="pending && !data" class="loading-wrapper">
      <Skeleton width="140px" height="140px" radius="50%" />
    </div>

    <!-- Chart Container -->
    <div ref="chartRef" v-show="!pending || data" class="gauge-chart" :class="{ 'dimmed': isError }"></div>

    <!-- Bottom Details -->
    <div v-if="data" class="gauge-details">
      <div v-for="(val, key) in data.details" :key="key" class="detail-item">
        <span class="label">{{ formatKey(key) }}:</span>
        <span class="value">{{ val }}</span>
      </div>
    </div>

    <!-- Error Overlay -->
    <div v-if="isError" class="error-overlay">
      <Icon name="lucide:refresh-cw" class="retry-icon" @click="fetchMetric" />
    </div>
  </div>
</template>

<script setup>
import { use } from 'echarts/core';
import { GaugeChart } from 'echarts/charts';
import { CanvasRenderer } from 'echarts/renderers';
import { GridComponent, TooltipComponent } from 'echarts/components';
import * as echarts from 'echarts/core';

// Register necessary components
use([GaugeChart, CanvasRenderer, GridComponent, TooltipComponent]);

const config = useRuntimeConfig();
const chartRef = ref(null);
let chartInstance = null;
const data = ref(null);
const pending = ref(true);
const isError = ref(false);
const isInitializing = ref(false);
let refreshInterval = null;
let themeObserver = null;

const fetchMetric = async () => {
  try {
    const response = await fetch(`${config.public.apiBase}/market-index`);
    
    if (response.status === 200) {
      const result = await response.json();
      data.value = result;
      isError.value = false;
      isInitializing.value = false;
      pending.value = false;
      setTimeout(() => updateChart(result.value), 0);
    } else if (response.status === 202) {
      isInitializing.value = true;
      isError.value = false;
      pending.value = false;
    } else {
      throw new Error('Server Error');
    }
  } catch (e) {
    console.error('Failed to fetch market index:', e);
    isError.value = true;
    isInitializing.value = false;
    pending.value = false;
  }
};

const formatKey = (key) => {
  const map = { rsi: 'RSI', vix: 'VIX', valuation: '估值', macro: '宏观' };
  return map[key] || key;
};

const updateChart = (value) => {
  if (!chartRef.value) return;
  if (!chartInstance) {
    chartInstance = echarts.init(chartRef.value);
  }
  
  const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
  const labelColor = isDark ? '#94a3b8' : '#64748b';
  
  const option = {
    series: [
      {
        type: 'gauge',
        startAngle: 190,
        endAngle: -10,
        center: ['50%', '70%'],
        radius: '100%',
        min: 0,
        max: 100,
        splitNumber: 5,
        axisLine: {
          lineStyle: {
            width: 6,
            color: [
              [0.3, '#10b981'],
              [0.5, '#34d399'],
              [0.7, '#fbbf24'],
              [0.85, '#f97316'],
              [1, '#ef4444']
            ]
          }
        },
        pointer: {
          icon: 'path://M12.8,0.7l12,10.1c0.4,0.3,0.4,0.9,0.1,1.2c-0.3,0.4-0.9,0.4-1.2,0.1L12,2.3L0.3,12.1c-0.4,0.3-0.9,0.3-1.2-0.1c-0.3-0.4-0.3-0.9,0.1-1.2L11.2,0.7C11.7,0.3,12.3,0.3,12.8,0.7z',
          length: '10%',
          width: 4,
          offsetCenter: [0, '-50%'],
          itemStyle: { color: isError.value ? '#64748b' : 'auto' }
        },
        axisTick: { show: false },
        splitLine: { show: false },
        axisLabel: {
          color: labelColor,
          fontSize: 9,
          distance: -40,
          formatter: function (v) {
            if (v === 15) return '极度恐惧';
            if (v === 85) return '极度贪婪';
            return '';
          }
        },
        detail: {
          fontSize: 18,
          offsetCenter: [0, '20%'],
          valueAnimation: true,
          formatter: '{value}',
          color: isError.value ? '#64748b' : 'auto',
          fontWeight: '800'
        },
        data: [{ value: value }]
      }
    ]
  };
  
  chartInstance.setOption(option);
};

const startPolling = () => {
  if (refreshInterval) clearInterval(refreshInterval);
  refreshInterval = setInterval(() => {
    if (document.visibilityState === 'visible') fetchMetric();
  }, 10 * 60 * 1000);
};

const handleVisibilityChange = () => {
  if (document.visibilityState === 'visible') {
    fetchMetric();
    startPolling();
  }
};

onMounted(() => {
  fetchMetric();
  startPolling();
  document.addEventListener('visibilitychange', handleVisibilityChange);
  
  themeObserver = new MutationObserver(() => {
    if (data.value) updateChart(data.value.value);
  });
  themeObserver.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] });
  
  window.addEventListener('resize', () => chartInstance?.resize());
});

onUnmounted(() => {
  if (refreshInterval) clearInterval(refreshInterval);
  document.removeEventListener('visibilitychange', handleVisibilityChange);
  if (themeObserver) themeObserver.disconnect();
  chartInstance?.dispose();
});
</script>

<style scoped>
.sentiment-gauge-container {
  background: var(--card-bg);
  border-radius: var(--radius-lg);
  padding: 0.75rem 1rem;
  box-shadow: var(--shadow-sm);
  border: 1px solid var(--border-color);
  display: flex;
  flex-direction: column;
  position: relative;
  transition: border-color 0.3s;
}

.sentiment-gauge-container.is-error {
  border-color: rgba(239, 68, 68, 0.3);
}

.gauge-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 0.15rem;
  color: var(--text-primary);
}

.title-group {
  display: flex;
  align-items: center;
  gap: 0.4rem;
}

.title-group h3 {
  font-size: 0.875rem;
}

.status-indicator {
  font-size: 0.55rem;
  font-weight: 700;
  padding: 0.05rem 0.3rem;
  border-radius: 0.2rem;
  text-transform: uppercase;
}

.status-indicator.error { background: rgba(239, 68, 68, 0.1); color: #ef4444; }
.status-indicator.warning { background: rgba(251, 191, 36, 0.1); color: #fbbf24; }

.gauge-chart {
  height: 110px;
  width: 100%;
  transition: filter 0.3s;
}

.gauge-chart.dimmed {
  filter: grayscale(1) opacity(0.5);
}

.loading-wrapper {
  height: 110px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.gauge-details {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 0.2rem;
  margin-top: 0.25rem;
  padding-top: 0.5rem;
  border-top: 1px dashed var(--border-color);
}

.detail-item {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.detail-item .label {
  font-size: 0.65rem;
  color: var(--text-secondary);
  margin-bottom: 0.1rem;
}

.detail-item .value {
  font-size: 0.75rem;
  font-weight: 700;
  color: var(--text-primary);
}

.error-overlay {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 10;
}

.retry-icon {
  width: 2rem;
  height: 2rem;
  color: var(--text-secondary);
  cursor: pointer;
  transition: transform 0.3s;
}

.retry-icon:hover {
  transform: rotate(180deg);
  color: var(--accent-color);
}
</style>
