// frontend/src/components/NasdaqTracker.tsx
"use client";

import React, { useState, useEffect, useCallback, useMemo } from "react";
import { Icon } from "@/components/ui/Icon";
import { Skeleton } from "@/components/ui/Skeleton";
import { cn } from "@/lib/utils";

interface NasdaqData {
  index: number;
  change: number;
  percent: number;
  last_update: string;
}

export const NasdaqTracker = () => {
  const [data, setData] = useState<NasdaqData | null>(null);
  const [isError, setIsError] = useState(false);
  const [isInitializing, setIsInitializing] = useState(false);

  const fetchNasdaq = useCallback(async () => {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 8000);

    try {
      const response = await fetch("/api/nasdaq", { 
        signal: controller.signal,
        headers: { "Cache-Control": "no-cache" }
      });
      clearTimeout(timeoutId);

      if (response.status === 200) {
        const result = await response.json();
        setData(result);
        setIsError(false);
        setIsInitializing(false);
      } else if (response.status === 202) {
        setIsInitializing(true);
        setIsError(false);
      } else {
        throw new Error("API Error");
      }
    } catch (e) {
      if (e instanceof Error && e.name !== "AbortError") {
        console.error("Nasdaq fetch error:", e);
        setIsError(true);
        setIsInitializing(false);
      }
    }
  }, []);

  useEffect(() => {
    fetchNasdaq();

    const interval = setInterval(() => {
      if (document.visibilityState === "visible") {
        fetchNasdaq();
      }
    }, 60 * 1000);

    const handleVisibilityChange = () => {
      if (document.visibilityState === "visible") {
        fetchNasdaq();
      }
    };

    document.addEventListener("visibilitychange", handleVisibilityChange);

    return () => {
      clearInterval(interval);
      document.removeEventListener("visibilitychange", handleVisibilityChange);
    };
  }, [fetchNasdaq]);

  const isLive = useMemo(() => {
    const now = new Date();
    const day = now.getUTCDay();
    const hour = now.getUTCHours();
    return day >= 1 && day <= 5 && hour >= 14 && hour < 21;
  }, []);

  const formatNumber = (val: number) => {
    return val.toLocaleString(undefined, { 
      minimumFractionDigits: 2, 
      maximumFractionDigits: 2 
    });
  };

  return (
    <div className={cn(
      "card relative overflow-hidden group",
      isError && "border-rose-200 dark:border-rose-900/30 bg-rose-50/10"
    )}>
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div className="space-y-4">
          <div className="flex items-center gap-3">
            <span className="text-[0.8rem] font-black text-[var(--text-secondary)] uppercase tracking-wider">
              NASDAQ 100
            </span>
            <span className="px-2 py-0.5 rounded-md bg-[var(--accent-soft)] text-[var(--accent-color)] text-[0.65rem] font-black">
              NDX
            </span>
            {isError && (
              <span className="px-2 py-0.5 rounded-md bg-rose-100 dark:bg-rose-900/30 text-rose-500 text-[0.65rem] font-bold animate-pulse">
                连接延迟
              </span>
            )}
            {isInitializing && !isError && (
              <span className="text-[0.65rem] font-bold text-amber-500 animate-pulse">
                同步中...
              </span>
            )}
          </div>

          <div className="price-area min-h-[3rem]">
            {data ? (
              <div className="space-y-1">
                <h2 className="text-5xl font-black tracking-tighter text-[var(--text-primary)] leading-none">
                  {formatNumber(data.index)}
                </h2>
                <div className={cn(
                  "flex items-center gap-2 text-[0.95rem] font-bold",
                  data.change >= 0 ? "text-emerald-500" : "text-rose-500"
                )}>
                  <Icon 
                    name={data.change >= 0 ? "lucide:trending-up" : "lucide:trending-down"} 
                    className="size-4" 
                  />
                  <span>{data.change >= 0 ? "+" : ""}{data.change.toFixed(2)}</span>
                  <span className="opacity-70">({data.change >= 0 ? "+" : ""}{data.percent.toFixed(2)}%)</span>
                </div>
              </div>
            ) : (
              <div className="space-y-3">
                <Skeleton width="180px" height="3rem" radius="0.75rem" />
                <Skeleton width="120px" height="1.25rem" />
              </div>
            )}
          </div>
        </div>

        <div className="flex flex-col items-end gap-3">
          <div className={cn(
            "flex items-center gap-2 px-3 py-1.5 rounded-full text-[0.7rem] font-bold transition-colors",
            isLive && !isError && !isInitializing
              ? "bg-emerald-500/10 text-emerald-500"
              : "bg-slate-100 dark:bg-slate-800 text-slate-500"
          )}>
            <div className={cn(
              "size-1.5 rounded-full bg-current",
              isLive && !isError && !isInitializing && "animate-pulse shadow-[0_0_8px_currentColor]"
            )} />
            {isError ? "服务离线" : (isInitializing ? "初始化" : (isLive ? "实时行情" : "已收盘"))}
          </div>
          
          {data && (
            <div className="text-[0.65rem] text-slate-400 font-medium">
              {isError ? "上个快照:" : "最后更新:"} {data.last_update}
            </div>
          )}
        </div>
      </div>

      {/* Error Overlay */}
      {isError && (
        <div className="absolute -top-4 -right-4 opacity-10 pointer-events-none">
          <Icon name="lucide:cloud-off" className="size-24 text-rose-500" />
        </div>
      )}
    </div>
  );
};

// frontend/app/components/NasdaqTracker.vue
<template>
  <div class="nasdaq-tracker card dark-mode" :class="{ 'is-offline': isError }">
    <div class="tracker-content">
      <div class="left">
        <div class="label-group">
          <span class="index-name">NASDAQ 100</span>
          <span class="index-symbol">NDX</span>
          <span v-if="isError" class="error-tag">连接延迟</span>
          <span v-else-if="isInitializing" class="sync-tag">同步中...</span>
        </div>
        
        <div v-if="data" class="price-group">
          <h2 class="current-price">{{ formatNumber(data.index) }}</h2>
          <div class="change-info" :class="data.change >= 0 ? 'up' : 'down'">
            <Icon :name="data.change >= 0 ? 'lucide:trending-up' : 'lucide:trending-down'" class="icon" />
            <span>{{ data.change >= 0 ? '+' : '' }}{{ data.change.toFixed(2) }}</span>
            <span class="percent">({{ data.change >= 0 ? '+' : '' }}{{ data.percent.toFixed(2) }}%)</span>
          </div>
        </div>
        
        <div v-else class="price-group">
          <Skeleton width="120px" height="2.5rem" style="margin-bottom: 0.5rem" />
          <Skeleton width="80px" height="1rem" />
        </div>
      </div>

      <div class="right">
        <div class="status-tag" :class="{ 'is-live': isLive && !isError && !isInitializing }">
          <span class="dot"></span>
          {{ isError ? '服务离线' : (isInitializing ? '初始化' : (isLive ? '实时行情' : '已收盘')) }}
        </div>
        <div v-if="data" class="update-time">
          {{ isError ? '上个快照:' : '最后更新:' }} {{ data.last_update }}
        </div>
      </div>
    </div>
    
    <!-- Background alert for errors -->
    <div v-if="isError" class="offline-overlay">
      <Icon name="lucide:cloud-off" class="offline-icon" />
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted, computed } from 'vue';

const config = useRuntimeConfig();
const data = ref(null);
const isError = ref(false);
const isInitializing = ref(false);
let refreshInterval = null;

const fetchNasdaq = async () => {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 8000); // 8s timeout

  try {
    const response = await fetch(`${config.public.apiBase}/nasdaq`, { signal: controller.signal });
    clearTimeout(timeoutId);

    if (response.status === 200) {
      const result = await response.json();
      data.value = result;
      isError.value = false;
      isInitializing.value = false;
    } else if (response.status === 202) {
      isInitializing.value = true;
      isError.value = false;
    } else {
      throw new Error('API Error');
    }
  } catch (e) {
    console.error('Nasdaq fetch error:', e);
    isError.value = true;
    isInitializing.value = false;
  }
};

const formatNumber = (val) => {
  return val.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
};

const isLive = computed(() => {
  const now = new Date();
  const day = now.getUTCDay();
  const hour = now.getUTCHours();
  return day >= 1 && day <= 5 && hour >= 14 && hour < 21;
});

const startPolling = () => {
  if (refreshInterval) clearInterval(refreshInterval);
  refreshInterval = setInterval(() => {
    if (document.visibilityState === 'visible') {
      fetchNasdaq();
    }
  }, 60 * 1000);
};

const handleVisibilityChange = () => {
  if (document.visibilityState === 'visible') {
    fetchNasdaq();
    startPolling();
  }
};

onMounted(() => {
  fetchNasdaq();
  startPolling();
  document.addEventListener('visibilitychange', handleVisibilityChange);
});

onUnmounted(() => {
  if (refreshInterval) clearInterval(refreshInterval);
  document.removeEventListener('visibilitychange', handleVisibilityChange);
});
</script>

<style scoped>
.nasdaq-tracker {
  background: var(--card-bg) !important;
  color: var(--text-primary) !important;
  border: 1px solid var(--border-color);
  padding: 2rem !important;
  border-radius: var(--radius-lg) !important;
  position: relative;
  overflow: hidden;
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
  box-shadow: var(--shadow-sm);
}

.nasdaq-tracker:hover {
  transform: translateY(-4px);
  box-shadow: var(--shadow-lg);
  border-color: var(--accent-color);
}

.current-price {
  font-size: 3rem;
  font-weight: 900;
  margin: 0;
  line-height: 1;
  letter-spacing: -0.04em;
  color: var(--text-primary);
}

.index-name {
  font-size: 0.85rem;
  font-weight: 800;
  color: var(--text-secondary);
  text-transform: uppercase;
}

.index-symbol {
  font-size: 0.7rem;
  background: var(--accent-soft);
  padding: 0.2rem 0.5rem;
  border-radius: 0.4rem;
  color: var(--accent-color);
  font-weight: 700;
}

.error-tag {
  font-size: 0.65rem;
  color: #f43f5e;
  font-weight: 700;
  background: rgba(244, 63, 94, 0.1);
  padding: 0.1rem 0.4rem;
  border-radius: 0.25rem;
}

.sync-tag {
  font-size: 0.65rem;
  color: #fbbf24;
  font-weight: 700;
}

.price-group {
  margin-top: 0.75rem;
}

.current-price {
  font-size: 2.25rem;
  font-weight: 800;
  margin: 0;
  line-height: 1;
}

.change-info {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  font-size: 0.9rem;
  font-weight: 600;
  margin-top: 0.5rem;
}

.change-info.up { color: #10b981; }
.change-info.down { color: #f43f5e; }

.right {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 0.5rem;
}

.status-tag {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  font-size: 0.7rem;
  font-weight: 600;
  padding: 0.25rem 0.6rem;
  background: #1e293b;
  border-radius: 2rem;
  color: #94a3b8;
}

.status-tag.is-live {
  color: #10b981;
  background: rgba(16, 185, 129, 0.1);
}

.dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: currentColor;
}

.status-tag.is-live .dot {
  box-shadow: 0 0 8px currentColor;
  animation: pulse 2s infinite;
}

.update-time {
  font-size: 0.65rem;
  color: #64748b;
}

.offline-overlay {
  position: absolute;
  top: -10px;
  right: -10px;
  opacity: 0.15;
}

.offline-icon {
  font-size: 4rem;
  color: #ef4444;
}

@keyframes pulse {
  0% { opacity: 1; }
  50% { opacity: 0.4; }
  100% { opacity: 1; }
}
</style>
