// frontend/src/components/ui/Skeleton.tsx
import React from "react";
import { cn } from "@/lib/utils";

interface SkeletonProps {
  className?: string;
  width?: string;
  height?: string;
  radius?: string;
  style?: React.CSSProperties;
}

export const Skeleton = ({ className, width, height, radius, style }: SkeletonProps) => {
  return (
    <div
      className={cn("animate-pulse bg-slate-200 dark:bg-slate-800", className)}
      style={{
        width: width || "100%",
        height: height || "1rem",
        borderRadius: radius || "0.5rem",
        ...style,
      }}
    />
  );
};

// frontend/app/components/Skeleton.vue
<template>
  <div 
    class="skeleton-pulse" 
    :style="{ 
      width: width, 
      height: height, 
      borderRadius: radius 
    }"
  ></div>
</template>

<script setup>
defineProps({
  width: { type: String, default: '100%' },
  height: { type: String, default: '1rem' },
  radius: { type: String, default: '0.5rem' }
});
</script>

<style scoped>
.skeleton-pulse {
  background: linear-gradient(
    90deg,
    #f1f5f9 25%,
    #e2e8f0 50%,
    #f1f5f9 75%
  );
  background-size: 200% 100%;
  animation: pulse 1.5s infinite linear;
}

@keyframes pulse {
  0% {
    background-position: 200% 0;
  }
  100% {
    background-position: -200% 0;
  }
}
</style>
