// frontend/app/pages/daily/[...slug].vue
<script setup lang="ts">
import { computed } from 'vue'

const route = useRoute()

// Slug handling for dynamic paths
const slug = computed(() => {
  return route.params.slug[0]
})

// Fetch from our new dynamic server API
const { data: page, error, pending } = await useFetch(`/cms/daily/${slug.value}`, {
  key: `daily-detail-${slug.value}`
})

useHead({
  title: page.value ? page.value.title : '每日信息',
  meta: [
    { name: 'description', content: page.value ? page.value.description : 'InvestCool 每日科技观察。' }
  ]
})
</script>

<template>
  <div class="daily-detail">
    <NuxtLink to="/daily" class="back-link">
      <Icon name="lucide:arrow-left" /> 返回列表
    </NuxtLink>

    <!-- Error State -->
    <div v-if="error || (!pending && !page)" class="error-state">
      <Icon name="lucide:file-question" class="error-icon" />
      <h3>简报未找到</h3>
      <p>抱歉，该内容可能尚未同步或已被移除。</p>
    </div>

    <article v-else-if="page" class="log-content">
      <header class="log-header">
        <div class="log-meta">
          <Icon name="lucide:calendar" class="icon" />
          {{ page.date }}
        </div>
        <h1 class="log-title">{{ page.title }}</h1>
        <p class="log-description">{{ page.description }}</p>
      </header>

      <div class="prose-wrapper prose-modern" v-html="page.html"></div>
    </article>

    <div v-else class="loading-state">
      <Skeleton width="100%" height="400px" />
    </div>
  </div>
</template>

<style scoped>
.daily-detail {
  padding-bottom: 5rem;
  max-width: 760px;
  margin: 0 auto;
}

.back-link {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  color: var(--text-secondary);
  text-decoration: none;
  font-size: 0.875rem;
  font-weight: 600;
  margin-bottom: 2rem;
  transition: color 0.2s;
}

.back-link:hover {
  color: var(--accent-color);
}

.log-header {
  margin-bottom: 3rem;
  border-bottom: 1px solid var(--border-color);
  padding-bottom: 2rem;
}

.log-meta {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.85rem;
  font-weight: 700;
  color: var(--accent-color);
  margin-bottom: 1rem;
}

.log-title {
  font-size: 2.25rem;
  font-weight: 800;
  line-height: 1.2;
  margin-bottom: 1rem;
  color: var(--text-primary);
}

.log-description {
  font-size: 1.1rem;
  color: var(--text-secondary);
  line-height: 1.6;
}

.error-state {
  text-align: center;
  padding: 5rem 0;
}

.error-icon {
  font-size: 3rem;
  color: #ef4444;
  margin-bottom: 1.5rem;
}

@media (max-width: 768px) {
  .log-title { font-size: 1.75rem; }
  .daily-detail { padding: 0 0.5rem 5rem; }
}
</style>

// frontend/src/app/(main)/ai/[slug]/page.tsx
import React from "react";
import Link from "next/link";
import { Icon } from "@/components/ui/Icon";
import { formatDate } from "@/lib/utils";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { getDocBySlug } from "@/lib/cms";

interface AIPageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: AIPageProps): Promise<Metadata> {
  const { slug } = await params;
  const article = await getDocBySlug("ai", slug);
  
  if (article) {
    return {
      title: article.title,
      description: article.description || "AI 赋能投资深度解析。",
    };
  }
  
  return { title: "AI Insights" };
}

export default async function AIDetailPage({ params }: AIPageProps) {
  const { slug } = await params;
  const article = await getDocBySlug("ai", slug);
  
  if (!article) {
    return notFound();
  }

  return (
    <div className="ai-detail-page pb-20 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <div className="max-w-[760px] mx-auto px-4 md:px-0">
        <header className="py-10">
          <Link href="/ai" className="inline-flex items-center gap-2 text-[var(--text-secondary)] hover:text-[var(--accent-color)] transition-colors no-underline font-bold text-sm mb-10 group">
            <Icon name="lucide:arrow-left" className="size-4 transition-transform group-hover:-translate-x-1" />
            返回列表
          </Link>

          <div className="space-y-6">
            <div className="flex items-center gap-3">
              <span className="px-3 py-1 rounded-lg bg-[var(--accent-soft)] text-[var(--accent-strong)] text-xs font-black uppercase">
                AI Insights
              </span>
              <span className="text-sm text-[var(--text-tertiary)] font-bold flex items-center gap-1.5">
                <Icon name="lucide:calendar" className="size-3.5" />
                {formatDate(article.date || article.created_at || new Date().toISOString())}
              </span>
            </div>

            <h1 className="text-4xl md:text-5xl font-black text-[var(--text-primary)] leading-tight">
              {article.title}
            </h1>
            
            {article.description && (
              <p className="text-xl text-[var(--text-secondary)] font-semibold leading-8">
                {article.description}
              </p>
            )}
          </div>
        </header>

        <article 
          className="prose-modern"
          dangerouslySetInnerHTML={{ __html: article.html }}
        />

        <footer className="mt-20 pt-10 border-t border-[var(--border-color)] text-center">
          <p className="text-xs text-[var(--text-tertiary)]">
            探索 AI 与投资的边界 @ InvestCool
          </p>
        </footer>
      </div>
    </div>
  );
}
