// frontend/src/app/(main)/tutorials/page.tsx
import React from "react";
import { PremiumPostCard } from "@/components/PremiumPostCard";
import { Metadata } from "next";
import { Icon } from "@/components/ui/Icon";
import { getCollection } from "@/lib/cms";

export const metadata: Metadata = {
  title: "架构与技术教程",
  description: "探索 InvestCool 的系统架构、优化之路及投资技术教程。",
};

export default async function TutorialsPage() {
  const data = await getCollection("tutorials");
  const tutorials = data.filter((item) => item.is_deleted !== "true" && item.is_deleted !== "True");

  return (
    <div className="tutorials-page space-y-12">
      <header className="page-header">
        <div className="inline-block px-3 py-1 bg-[var(--accent-soft)] text-[var(--accent-strong)] rounded-lg text-xs font-black uppercase mb-4">
          System Architecture
        </div>
        <h2 className="text-4xl font-black text-[var(--text-primary)] mb-2">
          架构与技术教程.
        </h2>
        <p className="text-[var(--text-secondary)] font-semibold max-w-2xl leading-7">
          深度解析 InvestCool 如何从单机博客进化为高可用 AI 投研平台。
        </p>
      </header>

      {tutorials.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 2xl:grid-cols-3 gap-8">
          {tutorials.map((item) => (
            <PremiumPostCard key={item.slug} article={item} />
          ))}
        </div>
      ) : (
        <div className="py-20 text-center border-2 border-dashed border-[var(--border-color)] rounded-lg">
          <Icon name="book-dashed" size={48} className="mx-auto mb-4 opacity-20" />
          <p className="text-[var(--text-tertiary)] italic">教程正在编写中，敬请期待...</p>
        </div>
      )}
    </div>
  );
}

// frontend/app/pages/tutorials/index.vue
<script setup lang="ts">
// Fetch all items from tutorials collection
const { data: allTutorials } = await useAsyncData('tutorials-list', () => 
  queryCollection('tutorials').all()
)

const tutorials = computed(() => {
  if (!allTutorials.value) return []
  return allTutorials.value.filter(a => a.is_deleted !== true && a.is_deleted !== 'True')
})

useHead({
  title: 'InvestCool 架构与教程',
  meta: [
    { name: 'description', content: '探索 InvestCool 的系统架构、优化之路及投资技术教程。' }
  ]
})
</script>

<template>
  <div class="tutorials-page">
    <header class="page-header">
      <div class="badge-accent">System Architecture</div>
      <h2 class="title">架构与技术教程</h2>
      <p class="subtitle">深度解析 InvestCool 如何从单机博客进化为高可用 AI 投研平台。</p>
    </header>

    <div class="tutorials-grid">
      <PremiumPostCard v-for="item in tutorials" :key="item.path" :article="item" />
    </div>

    <div v-if="!tutorials || tutorials.length === 0" class="empty-state">
      <Icon name="lucide:book-dashed" class="empty-icon" />
      <p>教程正在编写中，敬请期待...</p>
    </div>
  </div>
</template>

<style scoped>
.tutorials-page { padding-bottom: 5rem; animation: fadeIn 0.6s ease-out; }

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(10px); }
  to { opacity: 1; transform: translateY(0); }
}

.page-header { margin-bottom: 4rem; }

.badge-accent {
  display: inline-block;
  padding: 0.25rem 0.75rem;
  background: var(--accent-soft);
  color: var(--accent-color);
  border-radius: 4px;
  font-size: 0.7rem;
  font-weight: 800;
  text-transform: uppercase;
  margin-bottom: 1rem;
}

.title { font-size: 2.5rem; font-weight: 900; margin-bottom: 0.75rem; color: var(--text-primary); }
.subtitle { color: var(--text-secondary); font-size: 1.1rem; max-width: 600px; }

.tutorials-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
  gap: 2.5rem;
}

.empty-state { text-align: center; padding: 5rem 0; color: var(--text-tertiary); }
.empty-icon { font-size: 3.5rem; margin-bottom: 1rem; opacity: 0.2; }
</style>
